# Generated by Django 4.2.2 on 2026-02-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyageur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
