# Generated by Django 4.2.2 on 2026-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('voyageur', '0002_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyageur',
            name='email',
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='interests.interest'),
        ),
    ]
