# Generated by Django 4.2.2 on 2026-02-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_sitetouristique_type'),
        ('voyageur', '0003_remove_voyageur_email_alter_voyageur_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageur',
            name='favorite_sites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='sites.sitetouristique'),
        ),
    ]
