# Generated by Django 4.2.2 on 2026-02-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('voyageur', '0004_voyageur_favorite_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyageur',
            name='interests',
            field=models.ManyToManyField(blank=True, to='interests.interest'),
        ),
    ]
