# Generated by Django 4.2.2 on 2026-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_voyageur_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
