# Generated by Django 4.2.2 on 2026-02-20 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_activity_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_review_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_reviews', to='sites.sitetouristique'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
