# Generated by Django 4.2.2 on 2026-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Plage', 'Plage'), ('Montagne', 'Montagne'), ('Culture', 'Culture'), ('Aventure', 'Aventure'), ('Shopping', 'Shopping'), ('Histoire', 'Histoire')], max_length=50)),
                ('Tarif_d_entrée', models.CharField(blank=True, max_length=50, null=True)),
                ('Horaires', models.CharField(blank=True, max_length=50, null=True)),
                ('site_web', models.EmailField(max_length=254, unique=True)),
                ('Adresse', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activities', models.ManyToManyField(blank=True, to='sites.activity')),
                ('interests', models.ManyToManyField(blank=True, to='interests.interest')),
                ('similar_sites', models.ManyToManyField(blank=True, to='sites.sitetouristique')),
            ],
        ),
    ]
