# Generated by Django 4.2.2 on 2026-02-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_sitetouristique_city_sitetouristique_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetouristique',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='longitude',
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
