# Generated by Django 4.2.2 on 2026-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_sitetouristique_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.CharField(blank=True, choices=[('fas fa-walking', 'Hiking'), ('fas fa-shopping-bag', 'Swimming'), ('fas fa-utensils', 'Camping'), ('fas fa-theater-masks', 'Cycling'), ('fas fa-camera', 'Football'), ('fas fa-horse', 'Camping'), ('fas fa-spa', 'Cycling'), ('fas fa-paint-brus', 'Football')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='type',
            field=models.CharField(choices=[('Bien', 'Bien-être & Spa'), ('Sports', 'Sports & Aventure'), ('Plage', 'Plage'), ('Gastronomie', 'Gastronomie'), ('ville', 'ville'), ('Montagne', 'Montagne'), ('nature', 'nature'), ('history', 'history')], max_length=50),
        ),
    ]
