# Generated by Django 4.2.2 on 2026-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_activity_icon_alter_sitetouristique_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.CharField(blank=True, choices=[('fas fa-walking', 'Randonnée'), ('fas fa-shopping-bag', 'Shopping'), ('fas fa-utensils', 'Camping'), ('fas fa-theater-masks', 'Cyclisme'), ('fas fa-camera', 'Football'), ('fas fa-horse', 'Équitation'), ('fas fa-spa', 'Spa / Bien-être'), ('fas fa-paint-brus', 'Peinture')], max_length=120, null=True),
        ),
    ]
