# Generated by Django 4.2.2 on 2026-02-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_activity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetouristique',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
