# Generated by Django 4.2.2 on 2026-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_sitetouristique_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetouristique',
            name='type',
            field=models.CharField(choices=[('Bien_être_Spa', 'Bien-être & Spa'), ('Sports_Aventure', 'Sports & Aventure'), ('Plage', 'Plage'), ('Gastronomie', 'Gastronomie'), ('ville', 'ville'), ('Montagne', 'Montagne'), ('nature', 'nature'), ('history', 'history')], max_length=50),
        ),
    ]
