# Generated by Django 4.2.2 on 2026-02-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_sitetouristique_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetouristique',
            name='site_web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
